version: '2'
services:
  website:
    build: .
    command: uwsgi --http :57001 --wsgi-file /app/httpobs/website/main.py --processes 1 --callable app --master
    depends_on:
      - postgres
      - scanner
    environment:
      - HTTPOBS_DATABASE_HOST=postgres
      - HTTPOBS_DATABASE_PASS=httpobsapipassword
      - HTTPOBS_DATABASE_USER=httpobsapi
    links:
      - postgres
      - scanner
    ports:
      - "57001:57001"
    restart: always

  postgres:
    build: ./httpobs/database
    environment:
      - POSTGRES_USER=httpobs
      - POSTGRES_PASSWORD=totallyfakepassword
      - POSTGRES_DB=http_observatory

  scanner:
    build: ./httpobs/scanner
    command: functions-framework --target function --debug
